### ISSUE TITLE
v3.0.0 fails with TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by donovanmuller** [sindresorhus/gulp-zip#49]
2.0.3 works 100%.

Upgrade to 3.0.0 and get this:

```
[23:06:54] Using gulpfile ~/dev/git/lunchbug/site/gulpfile.js
[23:06:54] Starting 'zip'...

/home/xxx/lunchbug/site/node_modules/gulp-zip/node_modules/yazl/index.js:65
  entry.uncompressedSize = buffer.length;
                                 ^
TypeError: Cannot read property 'length' of null
    at ZipFile.addBuffer (/home/xxx/site/node_modules/gulp-zip/node_modules/yazl/index.js:65:34)
    at DestroyableTransform.through.obj.zip.end.zip.outputStream.pipe.concatStream.push.gutil.File.cwd [as _transform] (/home/xxx/site/node_modules/gulp-zip/index.js:33:7)

```

**Comment by thody** [comment]
+1

**Comment by wizraopeize** [comment]
+1

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-zip/issues/48
